FROM node as build

WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn cache clean && yarn --update-checksums
COPY . ./
RUN yarn && yarn build

# Stage - Production
FROM nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80 443

#Make sites-available directory
RUN mkdir "etc/nginx/sites-available"

# add nginx live config
ADD config/sandovalwedding2021-live.com /etc/nginx/sites-available/sandovalwedding2021.com

# create symlinks
RUN ln -s /etc/nginx/sites-available/sandovalwedding2021.com /etc/nginx/sites-enabled/sandovalwedding2021

# make certs dir as volume
VOLUME ["/etc/letsencrypt"]

CMD ["nginx", "-g", "daemon off;"]
